### ISSUE TITLE
A way to leave and restart the game

### ISSUE THREAD

**Issue by BCtopics** [chelsabeth/dungeon-crawl#14]
We need a way to leave the game. I'm thinking have the user type exit or x or something along those lines to leave the game. 

A similar situation for restarting. The user should be put back into the start of the game loop.

**Comment by Nevish-302** [comment]
can i have a go at it?

**Comment by BCtopics** [comment]
Sure, I’m not on GitHub right now but I’ll assign you in the morning. Feel free to start whenever though, I won't assign anyone else.

**Comment by BCtopics** [comment]
> can i have a go at it?

You've been assigned. Let me know if you need anything else.

**Comment by Nevish-302** [comment]
can you tell me how to execute it so that i can test it and add the option

**Comment by chelsabeth** [comment]
Hey @Nevish-302, there are a few ways you can test it. You can download an extension for the code editor you are using, or you can use an online tool such as this one: https://extendsclass.com/python.html

**Comment by Nevish-302** [comment]
I know how i can test a python file. But which file to execute to start the game? Or rather how can I start the game?

**Comment by BCtopics** [comment]
@Nevish-302 If you run the main.py in the terminal it should start. It's a terminal text adventure. Please make sure to pull the latest version as I've updated it a good bit. 

I've implemented the exit part already, you are welcome to do the restart part. This would just leave the script and execute the script again from scratch.

**Comment by Nevish-302** [comment]
I'm on it
